package investigate

import (
	"strings"
	"testing"

	"github.com/abdul-hamid-achik/vidtrace/internal/evidence"
)

func TestGitHubIssueFormat(t *testing.T) {
	t.Parallel()

	out := GitHubIssue(Report{
		OK:      true,
		Query:   "login failed",
		Summary: "Found 1 video evidence hit(s).",
		Evidence: []evidence.SearchResult{{
			TimeSeconds: 12.5,
			Frame:       "frames/frame_0013.png",
			OCRPath:     "ocr/frame_0013.txt",
			OCR:         "Login failed after submit",
		}},
		SuggestedQueries: []string{"login failed"},
	})
	for _, want := range []string{
		"## Bug evidence (vidtrace)",
		"**Query:** `login failed`",
		"### Timestamped evidence",
		"12.50s",
		"frames/frame_0013.png",
		"Generated by `vidtrace investigate`",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("GitHubIssue missing %q\n%s", want, out)
		}
	}
}

func TestFormatMarkdownDispatch(t *testing.T) {
	t.Parallel()

	report := Report{OK: true, Query: "x", Summary: "sum"}
	if !strings.Contains(FormatMarkdown(report, "github-issue"), "## Bug evidence") {
		t.Fatal("expected github-issue format")
	}
	if !strings.Contains(FormatMarkdown(report, "markdown"), "# Investigation Handoff") {
		t.Fatal("expected default markdown format")
	}
}
